# Generated by Django 4.1.7 on 2024-01-23 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='affairs',
            fields=[
                ('affairs_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headquarter', models.CharField(max_length=30, null=True)),
                ('center', models.CharField(max_length=30, null=True)),
                ('team', models.CharField(max_length=30, null=True)),
                ('affairs', models.CharField(max_length=30, null=True)),
                ('cust_no', models.CharField(max_length=30, null=True)),
                ('contract', models.CharField(max_length=30, null=True)),
                ('powertocost', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='affairspower',
            fields=[
                ('affairpowerid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('affairs', models.CharField(max_length=30, null=True)),
                ('power', models.FloatField(max_length=30, null=True)),
                ('cost', models.FloatField(max_length=30, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('affairs_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepco.affairs')),
            ],
        ),
        migrations.CreateModel(
            name='affairsbill',
            fields=[
                ('affairbill_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billdate', models.DateField(null=True)),
                ('mrdate', models.DateField(null=True)),
                ('bill_aply_power', models.FloatField(max_length=30, null=True)),
                ('base_bill', models.FloatField(max_length=30, null=True)),
                ('kwh_bill', models.FloatField(max_length=30, null=True)),
                ('dc_bill', models.FloatField(max_length=30, null=True)),
                ('req_bill', models.FloatField(max_length=30, null=True)),
                ('fianl_bill', models.FloatField(max_length=30, null=True)),
                ('lload_usekwh', models.FloatField(max_length=30, null=True)),
                ('mload_usekwh', models.FloatField(max_length=30, null=True)),
                ('maxload_usekwh', models.FloatField(max_length=30, null=True)),
                ('lload_needle', models.FloatField(max_length=30, null=True)),
                ('mload_needle', models.FloatField(max_length=30, null=True)),
                ('maxload_needle', models.FloatField(max_length=30, null=True)),
                ('jn_pwrfact', models.FloatField(max_length=30, null=True)),
                ('ji_pwrfact', models.FloatField(max_length=30, null=True)),
                ('affairs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepco.affairs')),
            ],
        ),
    ]
