# Generated by Django 4.1.7 on 2024-01-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affairsbill',
            name='affairbill_uuid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
