# Generated by Django 4.1.7 on 2024-01-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0002_alter_affairsbill_affairbill_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affairsbill',
            old_name='affairbill_uuid',
            new_name='affairbillid',
        ),
    ]
