# Generated by Django 4.1.7 on 2024-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0003_rename_affairbill_uuid_affairsbill_affairbillid'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairspower',
            name='isocanledar_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affairspower',
            name='isocanledar_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affairspower',
            name='isocanledar_year',
            field=models.IntegerField(null=True),
        ),
    ]
