# Generated by Django 4.1.7 on 2024-02-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0007_remove_affairspower_isocanledar_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairspower',
            name='isocanledar_year',
            field=models.IntegerField(null=True),
        ),
    ]
