# Generated by Django 4.1.7 on 2024-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0008_affairspower_isocanledar_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='affairsweekpower',
            fields=[
                ('weekpowerpk', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('isocanledar_year', models.IntegerField(null=True)),
                ('isocanledar_week', models.IntegerField(null=True)),
                ('powersum', models.FloatField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='affairspower',
            name='isreliability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affairspower',
            name='lastyearpower',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='affairspower',
            name='weekday',
            field=models.IntegerField(null=True),
        ),
    ]
