# Generated by Django 4.1.7 on 2024-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0009_affairsweekpower_affairspower_isreliability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairspower',
            name='time_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affairspower',
            name='time_minuter',
            field=models.IntegerField(null=True),
        ),
    ]
