# Generated by Django 4.1.7 on 2024-02-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0010_affairspower_time_hour_affairspower_time_minuter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affairspower',
            old_name='time_minuter',
            new_name='time_minute',
        ),
    ]
