# Generated by Django 4.1.7 on 2024-02-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0011_rename_time_minuter_affairspower_time_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairsweekpower',
            name='affairs',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='affairsweekpower',
            name='headquarter',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
