# Generated by Django 4.1.7 on 2024-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepco', '0012_affairsweekpower_affairs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairsweekpower',
            name='lastyearpowersum',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
